name: studie
description: A new Flutter project

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # easy_localization: ^3.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^5.0.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  speech_to_text: ^7.0.0
  googleapis: ^8.0.0
  googleapis_auth: ^1.0.0
  google_speech: ^2.0.0
  http: 0.13.6
  flutter_lints: ^4.0.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  share_plus: ^10.1.2
  cross_file: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  mockito: ^5.0.17
  firebase_auth_mocks: ^0.14.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
   